# Generated by Django 6.0.3 on 2026-03-26 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_event_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duration_hours',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
